# custom_exceptions.py

class StockAnalyzerError(Exception):
    pass
